copy_raw_html:
  type: bool
  default: false
  description: 'If selected the copied contents will be raw HTML instead of the stripped down plain text'
min_trust_level:
  type: enum
  default: disabled
  choices:
    - 'disabled'
    - '0'
    - '1'
    - '2'
    - '3'
    - '4'
  description: 'Select the minimum trust level required to see the widget.'
