copy_raw_html:
  type: bool
  default: false
  description: If selected the copied contents will be raw HTML instead of the stripped down plain text
  
min_trust_level:
  type: integer
  default: 0
  min: 0
  max: 5
  description: Show for this trust level (0-4) and below - Select (5) for everyone including not logged in
